Corrige pipeline quebrado em relação a URL tem todos os arquivos
parlametria/leggo-twitter-dados pull request #40
Opened 2022-03-31 20:15 UTC by andersonms1

# Descrição

Foi atualizado  as URLs:

`https://api.parlametria.org.br`
~`https://dev.api.parlametria.org.br`~

Em todos os arquivos, tanto para o `Makefile` e scripts `R`. 

# Issue

Closes #39

2022-03-31 20:46 UTC, ArthurJahn requested changes

2022-03-31 20:46 UTC, ArthurJahn commented on code/parlamentares/export_parlamentares.R
> +  make_option(c("-u", "--url"), type="character", default="https://dev.api.parlametria.org.br",
@andersonms1 as refs da ap ide dev antiga podem ser substituídas pela de produção, ok?

2022-03-31 21:40 UTC, andersonms1 commented on code/parlamentares/export_parlamentares.R
> +  make_option(c("-u", "--url"), type="character", default="https://dev.api.parlametria.org.br",
@ArthurJahn concertado :100:

2022-04-01 16:41 UTC, ArthurJahn requested changes

2022-04-01 16:41 UTC, ArthurJahn commented on code/parlamentares/export_parlamentares.R
> +export_parlamentares <- function(api_url = "https://dev.api.parlametria.org.br",
@andersonms1 todas essas refs de dev.api.parlametria devem apontar só pra api.parlametria , ok? Estou comentando nessa, mas pode substituir todas.

2022-04-01 16:42 UTC, ArthurJahn commented
Vou verificar a questão do pacote. No repo do RPostgres esse erro não aparece em nenhuma issue já aberta, te dou um retorno aqui

2022-04-01 18:50 UTC, andersonms1 commented
Percebi que em outros lugares a URL está errada tambem. Tudo bem atualizar a URL do ambiente de prod(https://api.parlametria.org.br) nesses locais tambem?  

`leggo-geral/stacks/backend.yml`
`leggo-painel/ngsw-config.json`
`leggo-painel/src/environments/environment.staging.ts`

@ArthurJahn

2022-04-01 19:15 UTC, ArthurJahn commented
> Percebi que em outros lugares a URL está errada tambem. Tudo bem atualizar a URL do ambiente de prod(https://api.parlametria.org.br) nesses locais tambem?
> 
> `leggo-geral/stacks/backend.yml` `leggo-painel/ngsw-config.json` `leggo-painel/src/environments/environment.staging.ts`
> 
> @ArthurJahn

Tudo bem atualizar! Pode fazer isso sim

2022-04-01 23:40 UTC, andersonms1 commented
## Consegui instalar o `Rpostgres`usando uma versão passada.
```shell
RUN R -e "install.packages(c('https://cran.r-project.org/src/contrib/Archive/RPostgres/RPostgres_1.3.3.tar.gz'), repos=NULL, type='"SOURCE"')"
```
A imagem que a gente usa com as depedencias do `R` é a `rocker/tidyverse:3.6.2` e a forma de instalar o `RPostgres` instalava a versões mais novas até o momento de incompatibilidade com  a imagem que é fixa na versão 3.6.2.

## Notei que  a URL errada tava sendo passada

O script `./update` do repo `leggo_geral` ao charmar  arquivos do R passa alguns argumentos, mas por algum motivo sempre o mesmo valor é usado, a URL antiga é passada `api.leggo.org.br`, mesmo não tendo ocorrência dela no código.
Por enquanto soluciono isso passado a URL com valor fixo

![image](https://user-images.githubusercontent.com/17951542/161354188-b5deeca6-b393-45b1-ab92-a67ea15ef528.png)

2022-04-02 00:14 UTC, andersonms1 commented
## Agora travei em um erro no container do `compose-api-leggo-twitter-1  |`

Ao executar o comando `make up-painel`   acontece o erro:

```shell
compose-api-leggo-twitter-1  | [nodemon] watching path(s): *.*
compose-api-leggo-twitter-1  | [nodemon] watching extensions: js,mjs,json
compose-api-leggo-twitter-1  | [nodemon] starting `node server.js`
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] undefined 
compose-api-leggo-twitter-1  | [info] Servidor rodando na porta 5001 
compose-api-leggo-twitter-1  | Executing (default): SELECT 1+1 AS result
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "parlamentar" ("id_parlamentar_parlametria" INTEGER , "id_parlamentar" INTEGER, "casa" VARCHAR(255), PRIMARY KEY ("id_parlamentar_parlametria"));
compose-api-leggo-twitter-1  | [info] Conexão com BD estabelecida com sucesso. 
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'parlamentar' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "tweet" ("id_tweet" VARCHAR(255) , "id_parlamentar_parlametria" INTEGER REFERENCES "parlamentar" ("id_parlamentar_parlametria") ON DELETE NO ACTION ON UPDATE CASCADE, "username" VARCHAR(255), "created_at" TIMESTAMP WITH TIME ZONE, "text" VARCHAR(255), "interactions" REAL, "url" VARCHAR(255), "outrage" REAL, "vagueness" REAL, "argumentation" REAL, "modalization" REAL, "valuation" REAL, "sentiment" REAL, "presupposition" REAL, PRIMARY KEY ("id_tweet"));
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'tweet' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "tema" ("id" INTEGER , "nome" VARCHAR(255), "slug" VARCHAR(255), PRIMARY KEY ("id"));
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'tema' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "proposicao" ("id_proposicao_leggo" VARCHAR(255) , "casa" VARCHAR(255), "casa_origem" VARCHAR(255), "sigla" VARCHAR(255), PRIMARY KEY ("id_proposicao_leggo"));
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'proposicao' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "tema_proposicao" ("id_proposicao_leggo" VARCHAR(255)  REFERENCES "proposicao" ("id_proposicao_leggo") ON DELETE CASCADE ON UPDATE CASCADE, "id_tema" VARCHAR(255)  REFERENCES "tema" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("id_proposicao_leggo","id_tema"));
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'tema_proposicao' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "tweet_proposicao" ("id_proposicao_leggo" VARCHAR(255)  REFERENCES "proposicao" ("id_proposicao_leggo") ON DELETE CASCADE ON UPDATE CASCADE, "id_tweet" VARCHAR(255)  REFERENCES "tweet" ("id_tweet") ON DELETE CASCADE ON UPDATE CASCADE, "sigla" VARCHAR(255) , "relator_proposicao" BOOLEAN , PRIMARY KEY ("id_proposicao_leggo","id_tweet","sigla","relator_proposicao"));
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'tweet_proposicao' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "agenda" ("id" INTEGER , "nome" VARCHAR(255), "slug" VARCHAR(255), PRIMARY KEY ("id"));
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'agenda' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-leggo-twitter-1  | Executing (default): CREATE TABLE IF NOT EXISTS "agenda_proposicao" ("id_proposicao_leggo" VARCHAR(255)  REFERENCES "proposicao" ("id_proposicao_leggo") ON DELETE CASCADE ON UPDATE CASCADE, "id_agenda" INTEGER  REFERENCES "agenda" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("id_proposicao_leggo","id_agenda"));
compose-api-leggo-twitter-1  | Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'agenda_proposicao' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
compose-api-legg [...]

2022-04-04 15:32 UTC, ArthurJahn commented
> Percebi que em outros lugares a URL está errada tambem. Tudo bem atualizar a URL do ambiente de prod(https://api.parlametria.org.br) nesses locais tambem?
> 
> `leggo-geral/stacks/backend.yml` `leggo-painel/ngsw-config.json` `leggo-painel/src/environments/environment.staging.ts`
> 

Sim, pode substituir tudo

2022-04-04 15:33 UTC, ArthurJahn commented
> 

@andersonms1  Esse problema foi corrigido no leggo-twitter, atualiza sua branch principal e verifica

2022-04-04 20:20 UTC, andersonms1 commented
## Ainda tenho um erro de migrations(eu acho)

Depois de atualizar a branch com `master` do repo `leggo-twitter` ainda acontece um erro. Acredito que seja das migrations do SQL.

```shell
./update_leggo_data.sh -update-db-twitter development
```

```shell
===============================
Iniciando atualização
===============================
seg 04 abr 2022 16:42:35 -03

===============================
Atualiza banco de dados do Twitter
===============================
Atualizando BD de desenvolvimento
BEGIN
psql:/code/scripts/migrations/0001_tweet_proposicao.sql:5: NOTICE:  column "relator_proposicao" of relation "tweet_proposicao" already exists, skipping
ALTER TABLE
COMMIT
BEGIN
psql:/code/scripts/migrations/0002_tema.sql:6: ERROR:  value too long for type character varying(80)
ROLLBACK
BEGIN
psql:/code/scripts/migrations/0003_tweet.sql:10: NOTICE:  column "vagueness" of relation "tweet" does not exist, skipping
psql:/code/scripts/migrations/0003_tweet.sql:10: NOTICE:  column "argumentation" of relation "tweet" does not exist, skipping
psql:/code/scripts/migrations/0003_tweet.sql:10: NOTICE:  column "modalization" of relation "tweet" does not exist, skipping
psql:/code/scripts/migrations/0003_tweet.sql:10: NOTICE:  column "valuation" of relation "tweet" does not exist, skipping
psql:/code/scripts/migrations/0003_tweet.sql:10: NOTICE:  column "sentiment" of relation "tweet" does not exist, skipping
psql:/code/scripts/migrations/0003_tweet.sql:10: NOTICE:  column "presupposition" of relation "tweet" does not exist, skipping
ALTER TABLE
COMMIT
BEGIN
psql:/code/scripts/migrations/0004_tweet.sql:5: NOTICE:  column "outrage" of relation "tweet" does not exist, skipping
ALTER TABLE
COMMIT
BEGIN
ALTER TABLE
psql:/code/scripts/migrations/0005_proposicao.sql:5: NOTICE:  column "destaque" of relation "proposicao" already exists, skipping
COMMIT
BEGIN
psql:/code/scripts/migrations/0006_tweet_raw_info.sql:10: NOTICE:  relation "tweet_raw_info" already exists, skipping
CREATE TABLE
COMMIT
BEGIN
ALTER TABLE
COMMIT
BEGIN
SELECT 0
COPY 593
INSERT 0 593
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 7
INSERT 0 7
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 2563
INSERT 0 2563
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 7
INSERT 0 7
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 96
INSERT 0 96
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 1591
INSERT 0 0
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 9
INSERT 0 9
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 2845
INSERT 0 0
DROP TABLE
COMMIT
BEGIN
SELECT 0
COPY 1
INSERT 0 1
DROP TABLE
COMMIT
seg 04 abr 2022 16:42:36 -03

===============================
Feito!
===============================

```

@ArthurJahn algum ideia do que pode ser?

2022-04-04 20:30 UTC, andersonms1 commented
```shell
make r-export-data url=https://api.parlametria.org.br
```

```shell
if [ -z "https://api.parlametria.org.br" ]; then echo "Insira uma url válida para API do Parlametria"; \
else echo "\nUsando a API: "https://api.parlametria.org.br; docker exec -it r-leggo-twitter bash -c "Rscript /leggo-twitter-dados/code/export_data.R -u https://api.parlametria.org.br"; fi
\nUsando a API: https://api.parlametria.org.br
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.2.1     ✔ purrr   0.3.3
✔ tibble  2.1.3     ✔ dplyr   0.8.4
✔ tidyr   1.0.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Loading required package: optparse
Use --help para mais informações

Recupera, processa e exporta dados de parlamentares, proposições e tweets
Use --help para mais informações

Anderson
********
https://api.parlametria.org.br
Iniciando processamento de parlamentares...
Baixando dados...
https://api.parlametria.org.br
Salvando o resultado em /leggo-twitter-dados/data/parlamentares/parlamentares.csv
Concluído!
Use --help para mais informações

Iniciando processamento de proposições...
Baixando dados...
[1] "Baixando proposições da agenda direitos-humanos..."
[1] "Baixando proposições da agenda leggo..."
[1] "Baixando proposições da agenda licenciamento-ambiental..."
[1] "Baixando proposições da agenda migracao-e-refugio..."
[1] "Baixando proposições da agenda pandemia..."
[1] "Baixando proposições da agenda reforma-administrativa..."
[1] "Baixando proposições da agenda reforma-tributaria..."
[1] "Baixando proposições da agenda socioambiental..."
[1] "Baixando proposições da agenda transparencia-e-integridade..."
Salvando o resultado em /leggo-twitter-dados/data/proposicoes/proposicoes.csv
Concluído!
Use --help para mais informações

Iniciando processamento de tweets...
Recuperando tweets...
Parsed with column specification:
cols(
  id_proposicao = col_character(),
  interesse_slug = col_character(),
  interesse_nome = col_character(),
  temas_nome = col_character(),
  temas_slug = col_character(),
  sigla = col_character(),
  casa = col_character(),
  casa_origem = col_character(),
  destaque = col_logical()
)
Salvando ids de tweets processados em /leggo-twitter-dados/data/tweets/tweets_processados.csv
Salvando o resultado em /leggo-twitter-dados/data/tweets/tweets.csv
Concluído!
Warning message:
Expected 2 pieces. Missing pieces filled with `NA` in 17 rows [2, 4, 5, 6, 10, 11, 12, 15, 16, 17, 20, 24, 26, 27, 30, 31, 33]. 
Use --help para mais informações


```

2022-04-05 01:33 UTC, andersonms1 commented
```shell
postgres-leggo-twitter       | 2022-04-04 22:15:01.534 -03 [106] ERROR:  value too long for type character varying(255)
postgres-leggo-twitter       | 2022-04-04 22:15:01.534 -03 [106] CONTEXT:  COPY temp_tweet, line 2, column text: "Enquanto isso, a cidade do Rio está abandonada! O distraído aumenta o IPTU, impede pessoas de trab..."
postgres-leggo-twitter       | 2022-04-04 22:15:01.534 -03 [106] STATEMENT:  COPY  temp_tweet FROM STDIN WITH NULL AS 'NA' DELIMITER ',' CSV HEADER;
postgres-leggo-twitter       | 2022-04-04 22:15:01.534 -03 [106] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres-leggo-twitter       | 2022-04-04 22:15:01.534 -03 [106] STATEMENT:  INSERT INTO tweet
postgres-leggo-twitter       | 	SELECT *
postgres-leggo-twitter       | 	FROM temp_tweet
postgres-leggo-twitter       | 	ON CONFLICT (id_tweet)
postgres-leggo-twitter       | 	DO
postgres-leggo-twitter       | 	  UPDATE
postgres-leggo-twitter       | 	  SET 
postgres-leggo-twitter       | 	    id_parlamentar_parlametria = EXCLUDED.id_parlamentar_parlametria,
postgres-leggo-twitter       | 	    username = EXCLUDED.username,
postgres-leggo-twitter       | 	    created_at = EXCLUDED.created_at,
postgres-leggo-twitter       | 	    text = EXCLUDED.text,
postgres-leggo-twitter       | 	    interactions = EXCLUDED.interactions,
postgres-leggo-twitter       | 	    url = EXCLUDED.url;
postgres-leggo-twitter       | 2022-04-04 22:15:01.534 -03 [106] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres-leggo-twitter       | 2022-04-04 22:15:01.534 -03 [106] STATEMENT:  DROP TABLE temp_tweet;
postgres-leggo-twitter       | 2022-04-04 22:15:01.566 -03 [108] ERROR:  insert or update on table "tweet_proposicao" violates foreign key constraint "tweet_proposicao_id_tweet_fkey"
postgres-leggo-twitter       | 2022-04-04 22:15:01.566 -03 [108] DETAIL:  Key (id_tweet)=(1506273924753104898) is not present in table "tweet".
postgres-leggo-twitter       | 2022-04-04 22:15:01.566 -03 [108] STATEMENT:  INSERT INTO tweet_proposicao
postgres-leggo-twitter       | 	SELECT *
postgres-leggo-twitter       | 	FROM temp_tweet_proposicao
postgres-leggo-twitter       | 	ON CONFLICT (id_tweet, id_proposicao_leggo)
postgres-leggo-twitter       | 	DO
postgres-leggo-twitter       | 	  UPDATE
postgres-leggo-twitter       | 	  SET 
postgres-leggo-twitter       | 	    sigla = EXCLUDED.sigla,
postgres-leggo-twitter       | 	    relator_proposicao = EXCLUDED.relator_proposicao;
postgres-leggo-twitter       | 2022-04-04 22:15:01.566 -03 [108] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres-leggo-twitter       | 2022-04-04 22:15:01.566 -03 [108] STATEMENT:  DROP TABLE temp_tweet_proposicao;

```

2022-04-05 19:31 UTC, ArthurJahn commented
Puts, esse sql do db parece estar muit odesatualizado

2022-04-06 03:18 UTC, andersonms1 commented
postgres-leggo-twitter       | 2022-04-05 22:31:49.914 -03 [1009] ERROR:  relation "tweet_raw" does not exist at character 17
postgres-leggo-twitter       | 2022-04-05 22:31:49.914 -03 [1009] STATEMENT:  SELECT r.* FROM tweet_raw AS r LEFT JOIN tweet_processado AS p ON r.id_tweet = p.id_tweet WHERE p.id_tweet IS NULL;
postgres-leggo-twitter       | 2022-04-05 22:32:20.423 -03 [1027] ERROR:  relation "tweet_processado" does not exist at character 58
postgres-leggo-twitter       | 2022-04-05 22:32:20.423 -03 [1027] STATEMENT:  CREATE TEMP TABLE temp_tweet_processado AS SELECT * FROM tweet_processado LIMIT 0;
postgres-leggo-twitter       | 2022-04-05 22:32:20.423 -03 [1027] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres-leggo-twitter       | 2022-04-05 22:32:20.423 -03 [1027] STATEMENT:  COPY  temp_tweet_processado FROM STDIN WITH NULL AS 'NA' DELIMITER ',' CSV HEADER;
postgres-leggo-twitter       | 2022-04-05 22:32:20.423 -03 [1027] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres-leggo-twitter       | 2022-04-05 22:32:20.423 -03 [1027] STATEMENT:  INSERT INTO tweet_processado
postgres-leggo-twitter       | 	SELECT *
postgres-leggo-twitter       | 	FROM temp_tweet_processado
postgres-leggo-twitter       | 	ON CONFLICT (id_tweet)
postgres-leggo-twitter       | 	DO NOTHING;
postgres-leggo-twitter       | 2022-04-05 22:32:20.424 -03 [1027] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres-leggo-twitter       | 2022-04-05 22:32:20.424 -03 [1027] STATEMENT:  DROP TABLE temp_tweet_processado;

2022-04-06 13:35 UTC, ArthurJahn commented
@andersonms1 você separou nesse MR só as alterações das urls? Abre uma issue nova pra resolvermos esses problemas de SQL

2022-04-06 13:35 UTC, ArthurJahn approved these changes

2022-04-11 18:37 UTC, merged